<?php

namespace app\common\controller;
use think\facade\Request;
use Elasticsearch\ClientBuilder;
use Elasticsearch\Common\Exceptions\TransportException;
class Elasticsearch extends Base{
    public $client = '';
    public $hosts = [
        '192.168.1.1:9200',         // IP + 端口
        '192.168.1.2',              // 仅 IP
        'mydomain.server.com:9201', // 域名 + 端口
        'mydomain2.server.com',     // 仅域名
        'https://localhost',        // 对 localhost 使用 SSL
        'https://192.168.1.3:9200'  // 对 IP + 端口 使用 SSL
    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->client = ClientBuilder::create()->setHosts($this->hosts)->build();
    }

    public function search($data){

        $client = ClientBuilder::create()->build();
        $params = [
            'index' => 'my_index',
            'type' => 'my_type',
            'id' => 'my_id',
            'body' => ['testField' => 'abc']
        ];

        try {
            $client->search($data);
        } catch (TransportException $e) {
            $previous = $e->getPrevious();
            echo $e->getMessage();
}

        $response = $client->index($params);
        print_r($response);
    }
}