<?php
/**
 * lemomall
 * ============================================================================
 * 版权所有 2019-2027 深圳市徕默科技有限公司，并保留所有权利。
 * 网站地址: https:www.lemomall.com
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * 如果商业用途务必到官方购买正版授权, 以免引起不必要的法律纠纷.
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: lemomall
 * Date: 2019/8/15
 */
namespace app\admin\controller;
use think\facade\Config;
use think\facade\Request;
use app\admin\model\AdminLog as LogModel;
use think\facade\View;
class AdminLog extends Base{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|string
     * @throws \think\db\exception\DbException
     */
    public function index(){

        if(Request::isPost()){
            $keys=Request::post('keys','','trim');
            $page = Request::post('page')?Request::post('page'):1;
            $list = LogModel::where('status',1)
               ->where('username|log_title','like','%'.$keys.'%')
               ->order('id desc')
               ->paginate(array('list_rows'=> $this->pageSize,'page'=>$page))
               ->toArray();
            if(!empty($list['data'])){
                foreach ($list['data'] as $k => $v) {
                    $useragent = explode('(', $v['log_agent']);
                    $list['data'][$k]['log_agent'] = $useragent[0];
                }
            }
            $result = ['code'=>0,'msg'=>'获取成功!','data'=>$list['data'],'count'=>$list['total']];
            return $result;
        }

        return View::fetch();
    }

    /**
     * @throws \Exception
     * 删除日志
     */
    public function delete(){

        if(LogModel::destroy(Request::post('id'))){
             $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }

    }

}
