<?php
/**
 * lemomall
 * ============================================================================
 * 版权所有 2019-2027 深圳市徕默科技有限公司，并保留所有权利。
 * 网站地址: https:www.lemomall.com
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * 如果商业用途务必到官方购买正版授权, 以免引起不必要的法律纠纷.
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: lemomall
 * Date: 2019/8/9
 */

namespace app\admin\controller;
use app\admin\model\AuthRule;
use think\facade\View;
use think\facade\Db;
use think\facade\Cache;
use think\Session;

class Index extends Base{

    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    /**
     * @return string
     * @throws \Exception
     * 首页
     */
    public function index(){
        // 所有显示的菜单；
        $menus = Cache::get('adminMenus');
        if(!$menus){
            $cate = AuthRule::where('menu_status',1)->order('sort asc')->select()->toArray();
            $menus = Menu::authMenu($cate);
            Cache::set('adminMenus',$menus);

        }
        $href = (string)url('main');
        $home = ["href"=>$href,"icon"=>"fa fa-home","title"=>"首页"];
        $menusinit =['menus'=>$menus,'home'=>$home];
        View::assign('menus',json_encode($menusinit));
        return View::fetch();

    }

    /**
     * @return string
     * @throws \think\db\exception\BindParamException
     * @throws \think\db\exception\PDOException
     * 主页面
     */
    public function main(){
        $version = Db::query('SELECT VERSION() AS ver');
        $config = Cache::get('main_config');
        if(!$config){
            $config  = [
                'url'             => $_SERVER['HTTP_HOST'],
                'document_root'   => $_SERVER['DOCUMENT_ROOT'],
                'document_protocol'   => $_SERVER['SERVER_PROTOCOL'],
                'server_os'       => PHP_OS,
                'server_port'     => $_SERVER['SERVER_PORT'],
                'server_ip'       => $_SERVER['REMOTE_ADDR'],
                'server_soft'     => $_SERVER['SERVER_SOFTWARE'],
                'server_file'     => $_SERVER['SCRIPT_FILENAME'],
                'php_version'     => PHP_VERSION,
                'mysql_version'   => $version[0]['ver'],
                'max_upload_size' => ini_get('upload_max_filesize'),
            ];
            Cache::set('main_config',$config,3600);
        }

        View::assign('config', $config);
        return View::fetch();
    }



}