<?php

namespace app\admin\controller;

use think\facade\Request;
use think\facade\View;
use app\common\model\Link as LinkModel;
use think\Validate;

class Link extends Base
{


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if (Request::isPost()) {
            $keys = Request::post('keys', '', 'trim');
            $page = Request::post('page') ? Request::post('page') : 1;
            $list = LinkModel::where('name', 'like', '%' . $keys . '%')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();

            return $result = ['code' => 0, 'msg' => '获取成功!', 'data' => $list['data'], 'count' => $list['total']];
        }

        return View::fetch();

    }

    public function add()
    {
        if (Request::isPost()) {
            $data = Request::post();
            try{
                $this->validate($data, 'Link');
            }catch (\Exception $e){
                $this->error($e->getMessage());
            }


            $res = LinkModel::create($data);
            if ($res) {
                $this->success('添加成功',url('index'));
            } else {
                $this->success('添加失败');
            }
        }
        $view = [
            'info' => '',
            'title' => '添加链接',
        ];
        View::assign($view);
        return View::fetch();
    }

    public function edit()
    {

        if (Request::isPost()) {
            $data = Request::post();
            try {
                $this->validate($data, 'Link');
            } catch (\Exception $e) {
                $this->error($e->getMessage());
            }
            $res = LinkModel::update($data);
            if ($res) {
                $this->success('修改成功', url('index'));
            } else {
                $this->success('修改失败');
            }
        }
        $info = LinkModel::find(Request::get('id'));
        $view = [
            'info' => $info,
            'title' => '修改链接',
        ];
        View::assign($view);
        return View::fetch('add');

    }

    public function delete()
    {
        $id = Request::post('id');
        if ($id) {

            LinkModel::destroy($id);
            $this->success('删除成功');
        } else {
            $this->error('删除失败');

        }


    }

    public function state()
    {
        $id = Request::post('id');
        if ($id) {
            $where['id'] = $id;

            $link = LinkModel::find($id);
            $where['status'] = $link['status'] ? 0 : 1;
            LinkModel::update($where);

            $this->success('修改成功');

        } else {
            $this->error('修改失败');

        }


    }
}