<?php

namespace app\admin\controller;
use think\facade\Request;
use think\facade\Db;
use think\facade\View;
class System extends Base {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //配置首页
    public function site()
    {
        if (Request::isPost()) {
            $data = Request::post();
            foreach ($data as $k=>$v){
               $res =  Db::name('config')->where('code',$k)->update(['value'=>$v]);
            }

            $this->success('保存成功');


        } else {
            $group =  ['site','email','upload','sms'];

                $list = Db::name('config')
                    ->where('type','in',$group)
                    ->field('code,value')
                    ->column('value','code');

            View::assign('config',json_encode($list));
            return View::fetch();
        }
    }

}